[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
core   = { path = "../core" }
chess  = { path = "../chess" }
engine = { path = "../engine" }
tensor = { path = "../tensor" }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
