[package]
name = "uci"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "uci"
path = "src/main.rs"

[dependencies]
engine = { path = "../engine" }
chess  = { path = "../chess" }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
